name: 'Bump version'
description: 'Greet someone and record the time'
inputs:
  file:
    description: 'Version file'
    required: true
  name:
    description: 'Project name'
    required: true
  version:
    description: 'Project version'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'